name: Email on Push to Main

on:
  push:
    branches:
      - main

jobs:

  send-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.EMAIL_USER}}
        password: ${{secrets.EMAIL_PASS}}
        subject: GitHub Actions - New Push to Main
        body: A new push has been made to the main branch.
        to: fatimaezzahrae.benhssain@usmba.ac.ma
        from: GitHub Actions
